name: Node CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
          - 20.x
          - 22.x
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check out test specs
        uses: actions/checkout@v4
        with:
          repository: 'karlvr/openapi-generator-plus-generators'
          path: 'test-input'
      # https://pnpm.io/continuous-integration
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - name: Use Node.js ${{ matrix.node-version }} for test
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm test
